version: '3.8'
services:
  controller:
    build: ./Controller
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - content:/app/content

  service:
    build: ./Service
    ports:
      - "8090:8090"
    networks:
      - mynetwork
    volumes:
      - content:/app/content

  repository:
    build: ./Repository
    ports:
      - "8070:8070"
    networks:
      - mynetwork
    volumes:
      - content:/app/content

networks:
  mynetwork:
    driver: bridge

volumes:
  content: